spring.application.name=campusfind

server.port=${PORT:8080} 

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/campusfind_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Shahid%279}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true 

spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
campusfind.upload.dir=uploads

campusfind.college.name=ABC College of Engineering
campusfind.app.name=CampusFind
campusfind.app.tagline=Lost. Found. Reunited.

logging.level.org.springframework.security=INFO
logging.level.com.campusfind=DEBUG